from selenium.webdriver.common.by import By

class MainPageLocators():
    guide = (By.XPATH,"//nav[@id='nav-website']//a[@href='/guide']")
    api = (By.XPATH,"//nav[@id='nav-website']//a[@href='/api']")
    dashboard = (By.XPATH,"//nav[@id='nav-website']//a[@href='/weather-dashboard']")
    market = (By.XPATH,"//nav[@id='nav-website']//a[@href='https://home.openweathermap.org/marketplace']")
    pricing = (By.XPATH, "//nav[@id='nav-website']//a[@href='/price']")
    maps = (By.XPATH, "//nav[@id='nav-website']//a[@href='/weathermap']")
    initiatives = (By.XPATH, "//nav[@id='nav-website']//a[@href='/our-initiatives']")
    partners = (By.XPATH, "//nav[@id='nav-website']//a[@href='/examples']")
    business = (By.XPATH, "//nav[@id='nav-website']//a[@href='https://openweather.co.uk']")
    sign_in = (By.XPATH,"//nav[@id='nav-website']//a[@href='https://openweathermap.org/home/sign_in']")
    blog = (By.XPATH,"//nav[@id='nav-website']//a[@href='https://openweather.co.uk/blog/category/weather']")
    email = (By.CSS_SELECTOR,"#user_email")
    password = (By.CSS_SELECTOR,"#user_password")
    submit = (By.XPATH,"//input[@class='btn btn-default btn-color']")
    input_city = (By.XPATH,"//input[@name='q']")
    home_page = (By.XPATH,"//nav[@id='nav-website']//img[@src='/themes/openweathermap/assets/img/logo_white_cropped.png']")
    support = (By.CSS_SELECTOR,"#support-dropdown")
    support_faq = (By.XPATH,"//ul[@class='dropdown-menu dropdown-visible']//a[@href='/faq']")
    support_start = (By.XPATH,"//ul[@class='dropdown-menu dropdown-visible']//a[@href='/appid']")
    support_chat = (By.XPATH, "//ul[@class='dropdown-menu dropdown-visible']//a[@href='/chat']")
    support_questions = (By.XPATH, "//ul[@class='dropdown-menu dropdown-visible']//a[@href='https://home.openweathermap.org/questions']")
    take_part = (By.XPATH, "//div[@class='left-section']//a[@href='https://challenge.openweather.co.uk/']")
    input_search_city = (By.XPATH,"//input[@placeholder='Search city']")
    button_search_city = (By.XPATH, "//button[@class='button-round dark']")
    choice_city_belgrade = (By.XPATH,"//ul[@class='search-dropdown-menu']//span[@style='width: 140px;']")
    button_close = (By.XPATH,"//span[@class='close-btn']")
    button_banner = (By.XPATH,"//button[@class='gdpr-banner__button--dismiss']")
    facebook = (By.XPATH,"//div[@class='social']//img[@alt='facebook icon']")
    twitter = (By.XPATH,"//div[@class='social']//img[@alt='x icon']")
    linkedin = (By.XPATH,"//div[@class='social']//img[@alt='linkedin icon']")
    medium = (By.XPATH, "//div[@class='social']//img[@alt='medium icon']")
    telegram = (By.XPATH, "//div[@class='social']//img[@alt='telegram icon']")
    git_hub = (By.XPATH, "//div[@class='social']//img[@alt='github icon']")
    app_store = (By.XPATH,"//div[@class='footer-section']//img[@alt='Get it on AppStore']")
    google_play = (By.XPATH, "//div[@class='footer-section']//img[@alt='Get it on Google Play']")
    current_location = (By.XPATH,"//div[@class='control-el']")
    fahrenheit = (By.XPATH, "//div[@class='switch-container']//div[@class='option']")
    celsium = (By.XPATH, "//div[@class='switch-container']//div[@class='option']")
    learn_more = (By.XPATH, "//div//a[@class='ow-btn round btn-black']")
    current_weather = (By.XPATH, "//div//img[@src='/themes/openweathermap/assets/img/landing/icon-1.png']")
    hourly_forecast = (By.XPATH, "//div//img[@src='/themes/openweathermap/assets/img/landing/icon-2.png']")
    daily_forecast = (By.XPATH, "//div//img[@src='/themes/openweathermap/assets/img/landing/icon-3.png']")
    climatic_forecast = (By.XPATH, "//div//img[@src='/themes/openweathermap/assets/img/landing/icon-4.png']")
    historical_weather = (By.XPATH, "//div//img[@src='/themes/openweathermap/assets/img/landing/icon-5.png']")
    footer_api = (By.XPATH, "//div[@class='footer-section']//a[@href='/api#current']")
    footer_history = (By.XPATH, "//div[@class='footer-section']//a[@href='/api#history']")
    footer_map = (By.XPATH, "//div[@class='footer-section']//a[@href='/api#maps']")
    footer_dash = (By.XPATH, "//div[@class='footer-section']//a[@href='/weather-dashboard']")
    footer_widgets = (By.XPATH, "//div[@class='footer-section']//a[@href='/widgets-constructor']")